logging:
  level:
    root: debug
security:
  jwt:
    expirationMinutes: 600000
    secretKey: thisIsAProjectForManageYourExpensesThatItsNameIsExpenseTracker
    refreshTokenExpirationDay: 1
spring:
  application:
    name: expense-tracker
  mail:
    host: smtp.gmail.com
    port: 587
    username: fatemehfathi409@gmail.com
    password: 6565215241
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    url: jdbc:h2:mem:expense-tracker-db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8020
